name: Build and deploy ASP.Net Core app to Azure Web App - VaccinationSystemSWDSpring2025

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: VaccinationSystemSWDSpring2025

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Restore
        run: dotnet restore backend/ChildrenVaccinationSystem.sln

      - name: Build
        run: dotnet build backend/ChildrenVaccinationSystem.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish backend/ChildrenVaccinationSystem.sln --configuration Release --no-restore --output ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "VaccinationSystemSWDSpring2025"
          slot-name: "Production"
          package: ${{env.DOTNET_ROOT}}/myapp
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
