name: Build and deploy ASP.Net Core app to Azure Web App - VaccinationSystemSWDSpring2025

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: VaccinationSystemSWDSpring2025
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Restore
        run: dotnet restore backend/ChildrenVaccinationSystem.sln

      - name: Build
        run: dotnet build backend/ChildrenVaccinationSystem.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish backend/ChildrenVaccinationSystem.sln --configuration Release --no-restore '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

      - name: deployment
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
